MySurvey/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import logout


from . import views

urlpatterns = [
               url(r'^login/$', auth_views.login, name='login'),
               url(r'^logout/$', auth_views.logout, {'next_page': '/login'}, name='logout'),
               url(r'^signup/$', views.signup, name='signup'),
               url(r'^(?P<product_id>[0-9]+)/$', views.detail, name='detail'),
               url(r'^update/$', views.update_profile, name='update_profile'),
               url(r'^home/$', views.home, name='home'),
               url(r'^path/$', views.path, name='path'),
               url(r'^programming/$', views.programming, name='programming'),
               url(r'^logoutandthankyou/$', auth_views.logout, {'next_page': '/thankyou'}, name='logoutandthankyou'),
               url(r'^thankyou/$', views.thankyou, name='thankyou'),
               url(r'^manage/$', views.manage, name='manage'),
               url(r'^manage/(?P<report_id>[0-9]+)/$', views.report, name='report'),
               url(r'^manage/(?P<report_id>[0-9]+)/user/(?P<user_id>[0-9]+)$', views.personalReport, name='personalReport'),
               ]

survey/urls.py
from django.conf.urls import url, include, handler404, handler500
from django.contrib.auth import views as auth_views
from django.contrib import admin

handler404 = 'kibosurvey.views.handler404'
handler500 = 'kibosurvey.views.handler500'

urlpatterns = [
    url(r'', include('kibosurvey.urls')),               
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    url(r'^admin/', admin.site.urls),
]

MySurvey/models.py
from __future__ import unicode_literals

from datetime import datetime

from django.db import models

from django.contrib.auth.models import User

from django.db.models.signals import post_save

from django.dispatch import receiver

from django.utils import timezone

# Create your models here.
class Profile(models.Model):
    
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    
    first_name = models.CharField(max_length=200, blank = True)
    
    last_name = models.CharField(max_length=200, blank = True)
    
    email = models.EmailField(max_length=254, blank = True)
    
    password = models.CharField(max_length=200, blank = True)

    def __str__(self):
        
        return 'Profile of user: %s' % (self.user.username)

@receiver(post_save, sender=User)

def create_user_profile(sender, instance, created, **kwargs):
    
    if created:
        
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)

def save_user_profile(sender, instance, **kwargs):
    
    instance.profile.save()


class Product(models.Model):

    product_name = models.CharField(max_length=200)
    
    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):

        return self.product_name


#Product question:
class Question(models.Model):
    
    product = models.ManyToManyField(Product)

    question_text = models.CharField(max_length=200)
    
    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):

        return self.question_text

#Programming question:
class ProgrammingQuestion(models.Model):

    programming_question_text = models.CharField(max_length=200)
    
    created_date = models.DateTimeField(default=timezone.now)
    
    def __str__(self):
        
        return self.programming_question_text



class Rating(models.Model):

    question =  models.ManyToManyField(Question)

    programming_question =  models.ManyToManyField(ProgrammingQuestion)

    rating_text = models.CharField(max_length=200)

    rating_number=models.IntegerField(default=0)

    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
    
        return self.rating_text


class productResults(models.Model):

    user_id_number = models.IntegerField(default=0)
    
    question_number = models.IntegerField(default=0)
    
    rating_number =  models.IntegerField(default=0)
    
    update_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
    
        return 'Results of user: %s, Question number: %s, rating_number: %s' % (self.user_id_number, self.question_number, self.rating_number)


class programmingResults(models.Model):
    
    user_id_number = models.IntegerField(default=0)
    
    question_number = models.IntegerField(default=0)
    
    rating_number =  models.IntegerField(default=0)
    
    update_date = models.DateTimeField(default=timezone.now)
    
    def __str__(self):
        
        return 'Results of user: %s, Question number: %s, rating_number: %s' % (self.user_id_number, self.question_number, self.rating_number)

MySurvey/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True, help_text='Required.')
    middle_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=True, help_text='Required.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')
    
    class Meta:
        model = User
        fields = ('username', 'first_name','middle_name', 'last_name', 'email', 'password1', 'password2', )


#class UserForm(forms.ModelForm):
#    class Meta:
#        model = User
#        fields = ('username','password')

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('first_name', 'last_name', 'email')



class PasswordResetRequestForm(forms.Form):
    email_or_username = forms.CharField(label=("Email Or Username"), max_length=254)


def username_present(username):
    
    if User.objects.filter(username=username).exists():
        return True
    
    return False

MySurvey/views.py
from django.http import HttpResponse
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .models import Profile, Product, Question, Rating, ProgrammingQuestion, productResults, programmingResults, User
from django.shortcuts import get_object_or_404, render
from .forms import SignUpForm, ProfileForm
from django.db import transaction
from django.contrib import messages
from datetime import datetime
import datetime
from django.utils import timezone
from django.contrib.auth.decorators import user_passes_test
import csv
from django.http import HttpResponse
from graphos.sources.simple import SimpleDataSource
from graphos.renderers.gchart import ColumnChart
from graphos.sources.model import ModelDataSource


def signup(request):
    
    if request.method == 'POST':
        
        form = SignUpForm(request.POST)
        
        if form.is_valid():
    
            form_email = form.cleaned_data.get('email')
        
            results = User.objects.filter(email = form_email)

            if results.count() == 0:


                form.save()
                
                username = form.cleaned_data.get('username')
                
                raw_password = form.cleaned_data.get('password1')

                user = authenticate(username=username, password=raw_password)
                

                login(request, user)
                
                profile = Profile.objects.get(user_id = user.id)
                
                profile.first_name = form.cleaned_data.get('first_name')
                
                profile.last_name = form.cleaned_data.get('last_name')
                
                profile.email =  form.cleaned_data.get('email')
                
                profile.password = raw_password
                    
                profile.save()

                return redirect('home')

            else:
                
                messages.error(request, 'Failed, your email has already been registed')

    else:
        
        form = SignUpForm()

    return render(request, 'registration/signup.html', {'form': form})

@login_required
@transaction.atomic
def update_profile(request):
    
    if request.method == 'POST':
        
        profile_form = ProfileForm(request.POST, instance=request.user.profile)
        
        if profile_form.is_valid():
            
            profile_form.save()
            
            messages.success(request, 'Your profile was successfully updated!')

            return redirect('home')

        else:
            
            messages.error(request, 'Please correct the error below.')
    else:
        
        profile_form = ProfileForm(instance=request.user.profile)
    
    return render(request, 'profiles/profile.html', {'profile_form': profile_form})


@login_required
def home(request):
    
    if request.user.is_superuser:
    
        return redirect('manage')
    
    else:

        product_list = Product.objects.order_by('-created_date')[:5]
        
        context = {'product_list': product_list}
        
        return render(request, 'home/startQuestion.html', context)


@login_required
@user_passes_test(lambda u: u.is_superuser)
def manage(request):
    if request.method == 'POST':
        
        profiles = Profile.objects.all()
        
        product_list = Product.objects.order_by('-created_date')[:5]
                
        productquestions= Question.objects.all()
                    
        programmingquestions= ProgrammingQuestion.objects.all()
        
        response = HttpResponse(content_type='text/csv')

        response['Content-Disposition'] = 'attachment; filename="report.csv"; '
        
        writer = csv.DictWriter(response, fieldnames=engineerList())
            
        writer.writeheader()
        
        output = engineerList(1)
        
        if request.POST.get('select') == '1':

            productresults = productResults.objects.filter(update_date__gte=datetime.date(2017, 5, 1), update_date__lte=datetime.date(2017, 8, 31))
    
            programmingresults = programmingResults.objects.filter(update_date__gte=datetime.date(2017, 5, 1), update_date__lte=datetime.date(2017, 8, 31))
            
            for product in product_list:
            
                for question in product.question_set.all():
            
                    output['Product'] = product.product_name
        
                    output['Question'] = question.question_text

                    for profile in profiles:
                        
                        m = outputs()
                        
                        if not profile.user.is_superuser:

                            value = m.product(profile.user.id, question.id, productresults)
            
                            name = profile.user.first_name + '_' +profile.user.last_name+'_'+profile.user.email

                            output[name] = value
    
                    writer.writerow(output)
        
            for pq in programmingquestions:
            
                output['Product'] = "Programming"
                
                output['Question'] = pq.programming_question_text
                    
                for profile in profiles:
                        
                    m = outputs()
                    
                    if not profile.user.is_superuser:
                    
                        value = m.programming(profile.user.id, pq.id, programmingresults)
                        
                        name = profile.user.first_name + '_' +profile.user.last_name+'_'+profile.user.email
                        
                        output[name] = value
                
                writer.writerow(output)
        
            return response


    return render(request, 'manage/manage.html')


@login_required
def detail(request, product_id):
    
    product = get_object_or_404(Product, pk=product_id)
    
    if request.method == 'POST':
    
        if 'continue' in request.POST:
            
            #validation
            for question in product.question_set.all():

                if request.POST.get(str(question.id)) is None:
                    
                    return render(request, 'home/detail.html', {
                                  'product': product,
                                  'error_message': "Please make sure you selected all choices",
                                  })

            for question in product.question_set.all():
                
                record =  productResults.objects.filter(user_id_number=request.POST.get("user"), question_number=question.id, update_date__gte=datetime.date(2017, 5, 1), update_date__lte=datetime.date(2017, 8, 31))
                
                if record.exists():
                    
                    record.update(rating_number = request.POST.get(str(question.id)), update_date = timezone.now())
                
                else:
                    
                    newRecord = productResults(user_id_number=request.POST.get("user"), question_number=question.id, rating_number =request.POST.get(str(question.id)))
            
                    newRecord.save()

            return redirect('path')

        elif 'back' in request.POST:
    
            return redirect('home')
                
    return render(request, 'home/detail.html', {'product': product})

@login_required
def programming(request):
    
    programmingQuestion = ProgrammingQuestion.objects.all()
    
    for test in programmingQuestion:
    
        print test.programming_question_text
    
    if request.method == 'POST':

        for pgquestion in programmingQuestion:

            if request.POST.get(str(pgquestion.id)) is None:
    
                return render(request, 'home/programming.html', {
                              'programmingQuestion': programmingQuestion,
                              'error_message': "Please make sure you selected all choices",
                              })

        for pgquestion in programmingQuestion:
                        
            record =  programmingResults.objects.filter(user_id_number=request.POST.get("user"), question_number=pgquestion.id, update_date__gte=datetime.date(2017, 5, 1), update_date__lte=datetime.date(2017, 8, 31))
                            
            if record.exists():
                
                record.update(rating_number = request.POST.get(str(pgquestion.id)), update_date = timezone.now())
                                            
            else:
                                                
                newRecord = programmingResults(user_id_number=request.POST.get("user"), question_number=pgquestion.id, rating_number =request.POST.get(str(pgquestion.id)))
                                                    
                newRecord.save()

        return redirect('logoutandthankyou')

    return render(request, 'home/programming.html', {'programmingQuestion': programmingQuestion})


@login_required
def path(request):
    
    if request.method == 'POST':
        
        if request.POST.get('select') == '1':
            
            return redirect('home')

        else:
            
            return redirect('programming')

    return render(request, 'home/pathQuestion.html')


def thankyou(request):

    return render(request, 'home/thankyou.html')



@login_required
@user_passes_test(lambda u: u.is_superuser)
def report(request, report_id):
    if report_id == '1':
        
        productresults = productResults.objects.filter(update_date__gte=datetime.date(2017, 5, 1), update_date__lte=datetime.date(2017, 8, 31))
        
        programmingresults = programmingResults.objects.filter(update_date__gte=datetime.date(2017, 5, 1), update_date__lte=datetime.date(2017, 8, 31))
        

MySurvey/templates/home/detail.html
{% extends 'base.html' %}
{% block content %}
<head>
    <style type="text/css">
        *{
            padding: 0;
        }
    form {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
    }
    ol {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
    }

    #radioGroup p {
        display: block;
        text-align: center;
        margin: 30px;
        margin-top:10px;
        margin-left:20px;
    }
    #radioGroup input[type="radio"] {
        display: block;
        margin: 0.5em auto;
    }
    #btn {
        top: 40px;
        position: relative;
        text-align:center;
        font-weight: 700;
        letter-spacing: 1px;
        text-transform: uppercase;
        flex-direction: row;
        justify-content: center;
        align-items: center;
        align-content: center;
    }
    #topic {
        text-align: center;
        margin-left:20px;
        margin-top:40px;
    }
    button{
         margin: 20px;
    }
    </style>
</head>
<div id="topic">
<h2>Q1, How would you rate your KIBO {{ product.product_name}} Knowledge?</h2>
<p><font size="3" style="color:blue">Please ANSWER all questions. 1---you have no idea about it. 10---you are the expert. </font></p>
</div>
<form name="survey" method="post">
    {% csrf_token %}
    <input type="hidden" name="user" value="{{user.id}}">
    <ul>
        {% if error_message %}<p><font color="red"><strong>{{ error_message }}</strong></font></p>{% endif %}
        {% for question in product.question_set.all %}
            <ol><li class="col-xs-12" value = "{{forloop.counter}}"><h3>{{question.question_text}}</h3></li></ol>
            <table class = "inputs_table">
                <tbody>
                    <tr>
                        {% for rating in question.rating_set.all %}
                        
                        <td>
                            <div id="radioGroup">
                                <div class="wrap">
                                        <p for="rating{{ forloop.counter }}">{{rating.rating_text}}</br>
                                        <input type="radio" name="{{ question.id }}" id="rating{{ forloop.counter }}" value="{{ rating.rating_number }}" /></p>
                                </div>
                            </div>
                        </td>
                        {% endfor %}
                    </tr>
                </tbody>
            </table>
        {% endfor %}
    </ul>
    <div id="btn">
    <button type="submit" name = 'continue' value = 'Continue'  class="btn btn-primary col-xs-12">Save and Continue</button>
    <button type="submit" name = 'back' value = 'Back'  class="btn btn-primary col-xs-12" >Go Back</button>
    </div>
</form>
{% endblock %}

MySurvey/templates/home/pathQuestion.html
{% extends 'base.html' %}
{% block content %}
<head>
    <style type="text/css">
        *{
            padding: 0;
        }
    form {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
    }
    ul {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
    }
    .labelgroup {
        display: inline-block;
        text-align: center;
        margin :20px;
    }
    #radioGroup input[type="radio"] {
        display: inline-block;
        margin: 0.5em auto;
    }
    #btn {
        top: 40px;
        position: relative;
        text-align:center;
        margin-left:20px;
        font-weight: 700;
        letter-spacing: 1px;
        text-transform: uppercase;
    }
    #topic {
        text-align: center;
        margin-top:40px;
    }
    </style>
</head>
<div id="topic">
<p><font size="3" style="color:gray">(Your information has been successfully saved)</font></p>
<h2>Are you familiar with other system?</h2>
</div>
<form method="post">
    {% csrf_token %}
     <ul>
        <div id="radioGroup">
            <div class="wrap">
                <input type="radio" name="select"  value="1"></input><label class="labelgroup">Yes--(Rate another system's knowledge)</label></br>
                <input type="radio" name="select" value="2" checked></input><label class="labelgroup">No---(Go to next question)</label>
                </br>
            </div>
        </div>
        <div id="btn">
        <input type="submit" class="btn btn-primary col-xs-12" value="Next" />
        </div>
    </ul>
   
</form>
{% endblock %}

MySurvey/templates/home/programming.html
{% extends 'base.html' %}
{% block content %}
<head>
    <style type="text/css">
    *{
        padding: 0;
    }
    form {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
    }
    ol {
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
    }

        
    #radioGroup p {
            display: block;
            text-align: center;
            margin: 30px;
            margin-left:20px;
            margin-top:10px
        }
    #radioGroup input[type="radio"] {
        display: block;
        margin: 0.5em auto;
    }
    #btn {
        top: 40px;
        position: relative;
        text-align:center;
        margin-left:20px;
        font-weight: 700;
        letter-spacing: 1px;
        text-transform: uppercase;
    }
    #topic {
        margin-top:40px;
        text-align: center;
    }
        </style>
</head>
<div id="topic">
<h2>Q2, Overall, how would you rate your knowledge on below programming skills ?</h2>
<p><font size="3" style="color:blue">Please ANSWER all questions. 1---you have no idea about it. 10---you are the expert. </font></p>
</div>
<form method="post">
    {% csrf_token %}
    {% if programmingQuestion %}
    <input type="hidden" name="user" value="{{user.id}}">
    <ul>
        {% if error_message %}<p><font color="red"><strong>{{ error_message }}</strong></font></p>{% endif %}
        {% for programming in programmingQuestion %}
            <ol><li class="col-xs-12" value = "{{forloop.counter}}"><h3>{{ programming.programming_question_text}}</h3></li></ol>
            <table class = "inputs_table">
                <tbody>
                    <tr>
                        {% for rating in programming.rating_set.all %}
                            <td>
                                <div id="radioGroup">
                                    <div class="wrap">
                                        <p for="rating{{ forloop.counter }}">{{rating.rating_text}}</br>
                                        <input type="radio" name="{{programming.id}}" id="rating{{ forloop.counter }}" value="{{ rating.rating_number }}" /></p>
                                    </div>
                                </div>
                            </td>
                         {% endfor %}
                    </td>
                </tbody>
            </table>
        {% endfor %}
    </ul>
    <div id="btn">
    <button type="submit" name = 'continue' value = 'Continue' class="btn btn-primary">Submit</button>
    </div>
    {% else %}
    <p>No programming question is available.</p>
    {% endif %}
    
</form>
{% endblock %}

MySurvey/templates/home/startQuestion.html
{% extends 'base.html' %}
{% block content %}
<head>
    <style type="text/css">
        form {
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }
        ul {
            display: flex;
            flex-direction: column;
            justify-content: center;
        }
        h2 {
            text-align: center;
            margin-top:40px;
        }
    
        li {
            margin-top:20px;
             float:left;
        }
    </style>
</head>
<h2>which below system are you most familar with?</h2>
<form method="post">
    {% csrf_token %}
    {% if product_list %}
        <ul>
        {% for product in product_list %}
            <li><a href="{% url 'detail' product.id %}"><font size = "5">{{ product.product_name}}</font></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No systems are available.</p>
    {% endif %}
</form>
{% endblock %}

MySurvey/templates/home/thankyou.html
{% extends 'base.html' %}

{% block content %}
<head>
    <style>
        h1 {
            text-align:center;
        }
    </style>
</head>
<div class="container" style="margin-top:5%;">
    <div class="row">
        <div class="jumbotron" style="box-shadow: 2px 2px 4px #000000;">
            <h2 class="text-center">Thank you for participate <span style="color:#FFCE01;">KI</span><span style="color:#656868;">BO</span><span style="color:#26A65B;">Survey</span></h2>
            <center><div class="btn-group" style="margin-top:50px;">
                <a href="{% url 'logout' %}" class="btn btn-lg btn-primary">Home</a>
                <a href="{% url 'logout' %}" class="btn btn-lg btn-default">Login</a>
            </div></center>
        </div>
    </div>
</div>
{% endblock %}